//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyDescription("Seq.App.InfluxDB")]
[assembly: AssemblyCompany("Andrew McClenaghan")]
[assembly: AssemblyProduct("Seq.App.InfluxDB")]
[assembly: AssemblyVersion("0.0.0.0")]
[assembly: AssemblyFileVersion("0.0.0.0")]
[assembly: AssemblyCopyright("Copyright (c) 2016")]

